version: '3.4'
services:
    puff-smith-staging:
        image: marekhanzal/puff-smith:edge
        env_file: .env
        networks:
            - web
            - db
            - memcached
        labels:
            - 'traefik.enable=true'
            # http stuff
            - 'traefik.http.routers.puff-smith-staging.rule=Host(`staging.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-staging.entrypoints=http'
            - 'traefik.http.routers.puff-smith-staging.middlewares=redirect-to-https'
            - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
            # https stuff
            - 'traefik.http.routers.puff-smith-staging-tls.rule=Host(`staging.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-staging-tls.entrypoints=https'
            - 'traefik.http.routers.puff-smith-staging-tls.tls=true'
            - 'traefik.http.routers.puff-smith-staging-tls.tls.certresolver=default'
            - 'traefik.http.services.puff-smith-staging-tls.loadbalancer.server.port=3000'

    memcached:
        image: memcached:1.6-alpine
        hostname: memcached
        networks:
            - memcached

    mariadb:
        image: mariadb:10
        hostname: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: puff-smith
            MYSQL_USER: puff-smith
            MYSQL_PASSWORD: 1234
        networks:
            - db

networks:
    web:
        external: true
    db:
    memcached:
