version: '2.0'
services:
    vapers-dream:
        # docker build -t marekhanzal/vapers-dream:edge .
        image: marekhanzal/vapers-dream:edge
        hostname: vapers-dream
        container_name: vapers-dream
        environment:
            - VERSION=docker-compose
            # good old ones
            - DATABASE_URL=jdbc:postgresql://postgres:5432/vapers-dream
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=1234
            # setup for the client where to find Discovery index and for server where the backend is running
            - BACKEND_HOST=http://localhost:8088
        ports:
            # client web application
            - "8080:3000"
            # backend server
            - "8088:8088"
        networks:
            # docker network create common --attachable
            - common

networks:
    common:
        external: true
