version: '2'
services:
    postgres:
        image: postgres:14.2
        restart: always
        env_file: docker-compose.env
        ports:
            - "5532:5432"
        networks:
            - postgres
            - mongo
            - mailhog

    mongo:
        image: mongo:5
        restart: always
        env_file: docker-compose.env
        ports:
            - "57017:27017"
        networks:
            - mongo

    agendash:
        image: agenda/agendash
        restart: always
        env_file: docker-compose.env
        depends_on:
            mongo:
                condition: "service_started"
        networks:
            - mongo
        ports:
            - "43000:3000"

    loki:
        image: grafana/loki
        restart: always
        networks:
            - loki
        ports:
            - "3100:3100"

    grafana:
        image: grafana/grafana-oss
        restart: always
        ports:
            - "5300:3000"
        networks:
            - loki

    redis:
        image: redis:6-alpine
        restart: always
        networks:
            - redis

    sentry:
        image: sentry
        env_file: docker-compose.env
        depends_on:
            postgres:
                condition: "service_started"
        ports:
            - 5900:9000

    sentry-cron:
        image: sentry
        command: "sentry run cron"
        env_file: docker-compose.env
        depends_on:
            redis:
                condition: 'service_started'
            postgres:
                condition: 'service_started'

    sentry-worker:
        image: sentry
        command: "sentry run worker"
        env_file: docker-compose.env
        depends_on:
            redis:
                condition: 'service_started'
            postgres:
                condition: 'service_started'

    #
    # Other services used in dev/staging
    #

    mailhog:
        image: mailhog/mailhog
        restart: always
        ports:
            - "5025:1025"
            - "5085:8025"

networks:
    postgres:
    redis:
    mongo:
    loki:
    mailhog:
