version: '2'
services:
    postgres:
        image: postgres:14.2
        restart: always
        env_file: docker-compose.env
        ports:
            - "5532:5432"
        networks:
            - postgres
            - sentry

    mongo:
        image: mongo:5
        restart: always
        env_file: docker-compose.env
        ports:
            - "57017:27017"
        networks:
            - mongo

    loki:
        image: grafana/loki
        restart: always
        networks:
            - loki
        ports:
            - "3100:3100"

    grafana:
        image: grafana/grafana-oss
        restart: always
        ports:
            - "5300:3000"
        networks:
            - loki

    redis:
        image: redis:6-alpine
        restart: always
        networks:
            - redis

    #
    # Other services used in dev/staging
    #

    mailhog:
        image: mailhog/mailhog
        restart: always
        ports:
            - "5025:1025"
            - "5085:8025"

networks:
    postgres:
    redis:
    mongo:
    loki:
    mailhog:
