version: '3.4'

x-environment:
  &env
    POSTGRES_USER: puff-smith
    POSTGRES_DB: puff-smith
    POSTGRES_PASSWORD: 1234

    MONGO_INITDB_ROOT_USERNAME: root
    MONGO_INITDB_ROOT_PASSWORD: 1234
    MONGO_INITDB_DATABASE: agenda

    MONGODB_URI: mongodb://root:1234@mongo:27017
    COLLECTION: agenda

    DATABASE_URL: postgres://puff-smith:1234@postgres:5432/postgres
    SECRET_KEY: secret-key
    PORT: 8000

services:
    postgres:
        image: postgres:14.2
        restart: always
        environment: *env
        ports:
            - "127.0.0.1:5532:5432"
        networks:
            - postgres
            - pgbouncer

    pgbouncer:
        image: bitnami/pgbouncer
        depends_on:
            - postgres
        environment:
            POSTGRESQL_HOST: postgres
            POSTGRESQL_USERNAME: puff-smith
            POSTGRESQL_PASSWORD: 1234
            POSTGRESQL_DATABASE: puff-smith
            PGBOUNCER_POOL_MODE: transaction
            PGBOUNCER_PORT: 6432
            PGBOUNCER_MIN_POOL_SIZE: 8
            PGBOUNCER_MAX_DB_CONNECTIONS: 16
            PGBOUNCER_IGNORE_STARTUP_PARAMETERS: 'extra_float_digits'
            PGBOUNCER_EXTRA_ARGS: '--verbose'
            PGBOUNCER_DATABASE: puff-smith
        ports:
            - "127.0.0.1:6532:6432"
        networks:
            - pgbouncer

    mongo:
        image: mongo:5
        restart: always
        environment: *env
        ports:
            - "127.0.0.1:57017:27017"
        networks:
            - mongo

    loki:
        image: grafana/loki
        restart: always
        networks:
            - loki
        ports:
            - "127.0.0.1:3100:3100"

    grafana:
        image: grafana/grafana-oss
        restart: always
        ports:
            - "127.0.0.1:5300:3000"
        volumes:
            - ./.local/grafana/provisioning:/etc/grafana/provisioning
        networks:
            - loki

    #
    # Other services used in dev/staging
    #

    mailhog:
        image: mailhog/mailhog
        restart: always
        networks:
            - mailhog
        ports:
            - "127.0.0.1:5025:1025"
            - "127.0.0.1:5085:8025"

networks:
    postgres:
    pgbouncer:
    redis:
    mongo:
    loki:
    mailhog:
