version: '2'
services:
    postgres:
        image: postgres:14.2
        restart: always
        ports:
            - "5532:5432"
        networks:
            - db
            - mongo
        environment:
            POSTGRES_USER: puff-smith
            POSTGRES_DB: puff-smith
            POSTGRES_PASSWORD: 1234

    mongo:
        image: mongo:5
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 1234
            MONGO_INITDB_DATABASE: agenda
        ports:
            - "47017:27017"
        networks:
            - mongo

    mongo-express:
        image: mongo-express
        restart: always
        depends_on:
            - mongo
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
            ME_CONFIG_MONGODB_URL: mongodb://root:1234@mongo:27017
        ports:
            - "48081:8081"
        networks:
            - mongo

    agendash:
        image: agenda/agendash
        restart: always
        depends_on:
            - mongo
        networks:
            - mongo
        ports:
            - "43000:3000"
        environment:
            MONGODB_URI: mongodb://root:1234@mongo:27017
            COLLECTION: agenda

networks:
    db:
    mongo:
