version: '2'
services:
    php:
        image: marekhanzal/php:8.1
        container_name: puff-smith
        hostname: puff-smith
        restart: always
        ports:
            - "5088:80"
            - "5022:22"
        volumes:
            - source:/var/www
        networks:
            - db
            - memcached
            - common

    memcached:
        image: memcached:1.6-alpine
        hostname: memcached
        networks:
            - memcached

    mariadb:
        image: mariadb:10
        hostname: mariadb
        ports:
            - "5306:3306"
        networks:
            - db
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: puff-smith
            MYSQL_USER: puff-smith
            MYSQL_PASSWORD: 1234

volumes:
    source:

networks:
    common:
        external: true
    db:
    memcached:
