version: '2'
services:
    php:
        image: marekhanzal/php:7.4
        container_name: puff-smith
        hostname: puff-smith
        restart: always
        ports:
            - "5088:80"
            - "5022:22"
        volumes:
            - source:/var/www
        networks:
            - common

volumes:
    source:

networks:
    common:
        external: true
