version: '2.0'
services:
    puff-smith:
        # docker build -t marekhanzal/puff-smith:edge .
        image: marekhanzal/puff-smith:edge
        hostname: puff-smith
        container_name: puff-smith
        environment:
            - VERSION=docker-compose
            # good old ones
            - DATABASE_URL=jdbc:postgresql://postgres:5432/puff-smith
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=1234
        ports:
            # client web application
            - "8080:3000"
            # backend server
            - "8088:8088"
        networks:
            # docker network create common --attachable
            - common

networks:
    common:
        external: true
