version: '2'
services:
    postgres:
        image: postgres:14.2
        restart: always
        ports:
            - "5532:5432"
        networks:
            - db
        environment:
            POSTGRES_USER: puff-smith
            POSTGRES_DB: puff-smith
            POSTGRES_PASSWORD: 1234

    adminer:
        image: adminer
        restart: always
        ports:
            - "5808:8080"
        networks:
            - db

networks:
    db:
