version: '3'
services:
    puff-smith:
        image: marekhanzal/puff-smith:latest
        depends_on:
            - mysql
        networks:
            - db
            - memcached
        ports:
            - "5388:3000"
            - "5088:80"

    memcached:
        image: memcached:1.6-alpine
        hostname: memcached
        networks:
            - memcached

    mariadb:
        image: mariadb:10
        hostname: mariadb
        ports:
            - "5306:3306"
        networks:
            - db
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: puff-smith
            MYSQL_USER: puff-smith
            MYSQL_PASSWORD: 1234

networks:
    db:
    memcached:
