version: '3.4'
services:
    traefik:
        image: traefik
        restart: always
        command:
#            - --api.insecure=true
            - --providers.docker
            - --providers.docker.exposedbydefault=false
            # docker network create web --attachable
            - --providers.docker.network=web
            - --entrypoints.http.address=:80
            - --entrypoints.https.address=:443
            - --certificatesresolvers.default.acme.tlschallenge=true
            # one used for experiments
#            - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
            - --certificatesresolvers.default.acme.email=acme@x32.cz
            - --certificatesresolvers.default.acme.storage=/letsencrypt/acme.json
#            - --log.level=debug
#        labels:
#            - 'traefik.enable=true'
#            - 'traefik.http.routers.api.rule=Host(`traefik.puff-smith.rocks`)'
#            - 'traefik.http.routers.api.service=api@internal'
        ports:
            - '80:80'
            - '443:443'
#            - '8080:8080'
        networks:
            - web
        volumes:
            - letsencrypt:/letsencrypt
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    letsencrypt:

networks:
    web:
        external: true
