version: '3.4'
services:
    traefik:
        image: traefik
        restart: always
        command: --api.insecure=true --providers.docker
        ports:
            - '80:80'
            - '443:443'
            - '8080:8080'
        volumes:
            #            - ./docker:/etc/traefik
            - /var/run/docker.sock:/var/run/docker.sock
