version: '3.4'
services:
    traefik:
        image: traefik
        restart: always
        command:
            - --api.insecure=true
            - --providers.docker
            - --providers.docker.exposedbydefault=false
            # docker network create web --attachable
            - --providers.docker.network=web
            - --entrypoints.http.address=:80
            - --entrypoints.https.address=:443
            - --certificateresolvers.lets-encrypt.acme.tlschallange=true
            - --certificateresolvers.lets-encrypt.acme.email=acme@puff-smith.rocks
            - --certificateresolvers.lets-encrypt.acme.storage=/lets-encrypt/acme.json
            - --log.level=debug
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.api.rule=Host(`traefik.puff-smith.rocks`)'
            - 'traefik.http.routers.api.service=api@internal'
        ports:
            - '80:80'
            - '443:443'
            - '8080:8080'
        networks:
            - web
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    web:
        external: true
