version: '3.4'
services:
    puff-smith:
        image: marekhanzal/puff-smith:edge
        env_file: .env
        #        environment:
        # good old ones
        #            - DATABASE_URL=jdbc:postgresql://postgres:5432/puff-smith
        #            - DATABASE_USER=postgres
        #            - DATABASE_PASSWORD=1234
        networks:
            - web
        labels:
            - 'traefik.enable=true'
            # http stuff
#            - 'traefik.http.routers.puff-smith.rule=Host(`puff-smith.rocks`)'
#            - 'traefik.http.routers.puff-smith.entrypoints=http'
#            - 'traefik.http.services.puff-smith.loadbalancer.server.port=3000'
            # https stuff
            - 'traefik.http.routers.puff-smith-tls.rule=Host(`puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-tls.entrypoints=https'
            - 'traefik.http.routers.puff-smith-tls.tls=true'
#            - 'traefik.http.routers.puff-smith-tls.tls.certresolver=lets-encrypt'
            - 'traefik.http.services.puff-smith-tls.loadbalancer.server.port=3000'

networks:
    web:
        external: true
