version: '3'
services:
    puff-smith-local:
        image: marekhanzal/puff-smith:latest
        depends_on:
            - mariadb
        environment:
            - PHINX=local
        networks:
            - db
            - memcached
        ports:
            - "42000:3000"

    memcached-local:
        image: memcached:1.6-alpine
        networks:
            - memcached

    mariadb-local:
        image: mariadb:10
        networks:
            - db
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: puff-smith
            MYSQL_USER: puff-smith
            MYSQL_PASSWORD: 1234

networks:
    db:
    memcached:
