version: '3.4'
services:
    puff-smith-production:
        image: marekhanzal/puff-smith:latest
        env_file: ../.env
        networks:
            - web
            - db
            - memcached
        labels:
            - 'traefik.enable=true'
            # http stuff
            - 'traefik.http.routers.puff-smith-production.rule=Host(`puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-production.entrypoints=http'
            - 'traefik.http.routers.puff-smith-production.middlewares=redirect-to-https'
            - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
            # https stuff
            - 'traefik.http.routers.puff-smith-production-tls.rule=Host(`puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-production-tls.entrypoints=https'
            - 'traefik.http.routers.puff-smith-production-tls.tls=true'
            - 'traefik.http.routers.puff-smith-production-tls.tls.certresolver=default'
            - 'traefik.http.services.puff-smith-production-tls.loadbalancer.server.port=3000'

    memcached:
        image: memcached:1.6-alpine
        hostname: memcached
        ports:
            - "3306:3306"
        networks:
            - memcached
            - web

    mariadb:
        image: mariadb:10
        hostname: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: puff-smith
            MYSQL_USER: puff-smith
            MYSQL_PASSWORD: 1234
        networks:
            - db
        volumes:
            - puff-smith-data:/var/lib/mysql

networks:
    web:
        external: true
    db:
    memcached:

volumes:
    puff-smith-data:
