version: '3'
services:
    app:
        image: marekhanzal/puff-smith:latest
        depends_on:
            - mariadb
        environment:
            PHINX: local
            DATABASE_URL: "mysql://puff-smith:1234@mariadb:3306/puff-smith"
        networks:
            - db
            - memcached
        ports:
            - "42000:3000"

    memcached:
        image: memcached:1.6-alpine
        hostname: memcached-local
        networks:
            - memcached

    mariadb:
        image: mariadb:10
        hostname: mariadb-local
        networks:
            - db
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: puff-smith
            MYSQL_USER: puff-smith
            MYSQL_PASSWORD: 1234

networks:
    db:
    memcached:
