version: '2'
services:
    app:
        image: marekhanzal/puff-smith:latest
        hostname: puff-smith
        depends_on:
            - mariadb
            - mongo
            - postgres
            - mailhog
        environment:
            DATABASE_URL: "postgresql://puff-smith:1234@postgres:5432/puff-smith?schema=public"
            NEXTAUTH_URL: 'http://localhost:42000'
            NEXTAUTH_SECRET: '1234'
            NEXTAUTH_GITHUB_CLIENT_ID: 'abbc01fc85709ab26921'
            NEXTAUTH_GITHUB_CLIENT_SECRET: 'd1d4c98417588b8280c60ee0b3b4233761d529f7'
            AGENDA_DB: root:1234@mongo:27017/?authSource=admin
            EMAIL_SERVER: smtp://mailhog:1025
            EMAIL_FROM: noreply@puff-smith.rocks
            LOKI_URL: "http://loki:3100"
        networks:
            - postgres
            - mongo
            - loki
            - prometheus
        ports:
            - "127.0.0.1:42000:3000"

    mongo:
        image: mongo:5
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 1234
            MONGO_INITDB_DATABASE: agenda
        ports:
            - "127.0.0.1:47017:27017"
        networks:
            - mongo

    postgres:
        image: postgres:14.2
        ports:
            - "127.0.0.1:42532:5432"
        networks:
            - postgres
        environment:
            POSTGRES_USER: puff-smith
            POSTGRES_DB: puff-smith
            POSTGRES_PASSWORD: 1234

    loki:
        image: grafana/loki
        networks:
            - loki

    grafana:
        image: grafana/grafana-oss
        ports:
            - "127.0.0.1:42300:3000"
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning
        networks:
            - loki
            - prometheus

    prometheus:
        image: prom/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        networks:
            - prometheus
        ports:
            - "127.0.0.1:45090:9090"
        volumes:
            - ./prometheus:/etc/prometheus

    mailhog:
        image: mailhog/mailhog
        ports:
            - "127.0.0.1:42080:8025"

networks:
    postgres:
    mongo:
    loki:
    prometheus:
    mailhog:
