version: '3'
services:
    app:
        image: marekhanzal/puff-smith:latest
        hostname: puff-smith
        depends_on:
            - mariadb
        environment:
            DATABASE_URL: "postgresql://puff-smith:1234@postgres:5432/puff-smith?schema=public"
            NEXTAUTH_URL: 'http://localhost:42000'
            NEXTAUTH_SECRET: '1234'
            NEXTAUTH_GITHUB_CLIENT_ID: 'abbc01fc85709ab26921'
            NEXTAUTH_GITHUB_CLIENT_SECRET: 'd1d4c98417588b8280c60ee0b3b4233761d529f7'
        networks:
            - db
        ports:
            - "42000:3000"

    postgres:
        image: postgres:14.2
        ports:
            - "42532:5432"
        networks:
            - db
        environment:
            POSTGRES_USER: puff-smith
            POSTGRES_DB: puff-smith
            POSTGRES_PASSWORD: 1234

    adminer:
        image: adminer
        ports:
            - "42080:8080"
        networks:
            - db

networks:
    db:
