version: '3'
services:
    app:
        image: marekhanzal/puff-smith:latest
        depends_on:
            - mariadb
        environment:
            DATABASE_URL: "postgresql://puff-smith:1234@postgrees:5432/puff-smith?schema=public"
        networks:
            - db
        ports:
            - "42000:3000"

    postgres:
        image: postgres:14.2
        ports:
            - "42532:5432"
        networks:
            - db
        environment:
            POSTGRES_USER: puff-smith
            POSTGRES_DB: puff-smith
            POSTGRES_PASSWORD: 1234

    adminer:
        image: adminer
        ports:
            - "42080:8080"
        networks:
            - db

networks:
    db:
