version: '3.4'
services:
    app:
        image: marekhanzal/puff-smith:latest
        env_file: .env
        networks:
            - web
        labels:
            - 'traefik.enable=true'
            # http stuff
            - 'traefik.http.routers.puff-smith-production.rule=Host(`puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-production.entrypoints=http'
            - 'traefik.http.routers.puff-smith-production.middlewares=redirect-to-https'
            - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
            # https stuff
            - 'traefik.http.routers.puff-smith-production-tls.rule=Host(`puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-production-tls.entrypoints=https'
            - 'traefik.http.routers.puff-smith-production-tls.tls=true'
            - 'traefik.http.routers.puff-smith-production-tls.tls.certresolver=default'
            - 'traefik.http.services.puff-smith-production-tls.loadbalancer.server.port=3000'
        volumes:
            - puff-smith-files:/var/www/.data

networks:
    web:
        external: true

volumes:
    puff-smith-data:
    puff-smith-files:
