version: '3.4'
services:
    app:
        image: marekhanzal/puff-smith:beta
        env_file: .env
        networks:
            - web
            - postgres
            - pgbouncer
            - loki
            - prometheus
            - mailhog
        labels:
            - 'traefik.enable=true'
            # http stuff
            - 'traefik.http.routers.puff-smith-beta.rule=Host(`beta.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-beta.entrypoints=http'
            - 'traefik.http.routers.puff-smith-beta.middlewares=redirect-to-https'
            - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
            # https stuff
            - 'traefik.http.routers.puff-smith-beta-tls.rule=Host(`beta.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-beta-tls.entrypoints=https'
            - 'traefik.http.routers.puff-smith-beta-tls.tls=true'
            - 'traefik.http.routers.puff-smith-beta-tls.tls.certresolver=default'
            - 'traefik.http.services.puff-smith-beta-tls.loadbalancer.server.port=3000'
        volumes:
            - "puff-smith-data:/opt/app/.data"

    postgres:
        image: postgres:14.2
        env_file: .env
        networks:
            - postgres
        environment:
            POSTGRES_USER: puff-smith
            POSTGRES_DB: puff-smith
        volumes:
            - "puff-smith-postgres:/var/lib/postgresql/data"

    pgbouncer:
        image: bitnami/pgbouncer
        env_file: .env
        depends_on:
            - postgres
        environment:
            POSTGRESQL_HOST: postgres
            POSTGRESQL_DATABASE: puff-smith
            POSTGRESQL_USERNAME: puff-smith
            PGBOUNCER_POOL_MODE: transaction
            PGBOUNCER_PORT: 6432
            PGBOUNCER_MIN_POOL_SIZE: 16
            PGBOUNCER_MAX_DB_CONNECTIONS: 42
            PGBOUNCER_IGNORE_STARTUP_PARAMETERS: 'extra_float_digits'
            PGBOUNCER_EXTRA_ARGS: '--verbose'
            PGBOUNCER_DATABASE: puff-smith
        networks:
            - postgres
            - pgbouncer

    loki:
        image: grafana/loki
        restart: always
        networks:
            - loki

    grafana:
        image: grafana/grafana-oss
        networks:
            - web
            - loki
            - prometheus
        volumes:
            - ./grafana/provisioning:/etc/grafana/provisioning
        labels:
            - 'traefik.enable=true'
            # http stuff
            - 'traefik.http.routers.puff-smith-alfa-grafana.rule=Host(`grafana.beta.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-alfa-grafana.entrypoints=http'
            - 'traefik.http.routers.puff-smith-alfa-grafana.middlewares=redirect-to-https'
            - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
            # https stuff
            - 'traefik.http.routers.puff-smith-alfa-grafana-tls.rule=Host(`grafana.beta.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-alfa-grafana-tls.entrypoints=https'
            - 'traefik.http.routers.puff-smith-alfa-grafana-tls.tls=true'
            - 'traefik.http.routers.puff-smith-alfa-grafana-tls.tls.certresolver=default'
            - 'traefik.http.services.puff-smith-alfa-grafana-tls.loadbalancer.server.port=3000'

    prometheus:
        image: prom/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
        networks:
            - prometheus
        volumes:
            - ./prometheus:/etc/prometheus

    mailhog:
        image: mailhog/mailhog
        networks:
            - web
            - mailhog
        labels:
            - 'traefik.enable=true'
            # http stuff
            - 'traefik.http.routers.puff-smith-beta-mailhog.rule=Host(`mail.beta.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-beta-mailhog.entrypoints=http'
            - 'traefik.http.routers.puff-smith-beta-mailhog.middlewares=redirect-to-https'
            - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
            # https stuff
            - 'traefik.http.routers.puff-smith-beta-mailhog-tls.rule=Host(`mail.beta.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-beta-mailhog-tls.entrypoints=https'
            - 'traefik.http.routers.puff-smith-beta-mailhog-tls.tls=true'
            - 'traefik.http.routers.puff-smith-beta-mailhog-tls.tls.certresolver=default'
            - 'traefik.http.services.puff-smith-beta-mailhog-tls.loadbalancer.server.port=8025'

networks:
    web:
        external: true
    postgres:
    pgbouncer:
    loki:
    prometheus:
    mailhog:

volumes:
    puff-smith-data:
    puff-smith-postgres:
