version: '3.4'
services:
    app:
        image: marekhanzal/puff-smith:beta
        env_file: .env
        networks:
            - web
            - postgres
            - mongo
            - mailhog
        labels:
            - 'traefik.enable=true'
            # http stuff
            - 'traefik.http.routers.puff-smith-beta.rule=Host(`beta.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-beta.entrypoints=http'
            - 'traefik.http.routers.puff-smith-beta.middlewares=redirect-to-https'
            - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
            # https stuff
            - 'traefik.http.routers.puff-smith-beta-tls.rule=Host(`beta.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-beta-tls.entrypoints=https'
            - 'traefik.http.routers.puff-smith-beta-tls.tls=true'
            - 'traefik.http.routers.puff-smith-beta-tls.tls.certresolver=default'
            - 'traefik.http.services.puff-smith-beta-tls.loadbalancer.server.port=3000'
        volumes:
            - "puff-smith-data:/opt/app/.data"

    postgres:
        image: postgres:14.2
        env_file: .env
        networks:
            - postgres
        environment:
            POSTGRES_USER: puff-smith
            POSTGRES_DB: puff-smith
        volumes:
            - "puff-smith-postgres:/var/lib/postgresql/data"

    mongo:
        image: mongo:5
        env_file: .env
        environment:
            MONGO_INITDB_DATABASE: agenda
        networks:
            - mongo

    mailhog:
        image: mailhog/mailhog
        networks:
            - web
            - mailhog
        labels:
            - 'traefik.enable=true'
            # http stuff
            - 'traefik.http.routers.puff-smith-beta-mailhog.rule=Host(`mail.beta.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-beta-mailhog.entrypoints=http'
            - 'traefik.http.routers.puff-smith-beta-mailhog.middlewares=redirect-to-https'
            - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
            # https stuff
            - 'traefik.http.routers.puff-smith-beta-mailhog-tls.rule=Host(`mail.beta.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-beta-mailhog-tls.entrypoints=https'
            - 'traefik.http.routers.puff-smith-beta-mailhog-tls.tls=true'
            - 'traefik.http.routers.puff-smith-beta-mailhog-tls.tls.certresolver=default'
            - 'traefik.http.services.puff-smith-beta-mailhog-tls.loadbalancer.server.port=8025'

networks:
    web:
        external: true
    postgres:
    mongo:
    mailhog:

volumes:
    puff-smith-data:
    puff-smith-postgres:
