version: '3.4'
services:
    puff-smith-staging:
        image: marekhanzal/puff-smith:staging
        env_file: .env
        environment:
            AGENDA_DB: ${AGENDA_DB}
            DATABASE_URL: ${DATABASE_URL}
            NEXTAUTH_GITHUB_CLIENT_ID: ${NEXTAUTH_GITHUB_CLIENT_ID}
            NEXTAUTH_GITHUB_CLIENT_SECRET: ${NEXTAUTH_GITHUB_CLIENT_SECRET}
            NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
            NEXTAUTH_URL: ${NEXTAUTH_URL}
        networks:
            - web
            - db
            - mongo
        labels:
            - 'traefik.enable=true'
            # http stuff
            - 'traefik.http.routers.puff-smith-staging.rule=Host(`staging.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-staging.entrypoints=http'
            - 'traefik.http.routers.puff-smith-staging.middlewares=redirect-to-https'
            - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
            # https stuff
            - 'traefik.http.routers.puff-smith-staging-tls.rule=Host(`staging.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-staging-tls.entrypoints=https'
            - 'traefik.http.routers.puff-smith-staging-tls.tls=true'
            - 'traefik.http.routers.puff-smith-staging-tls.tls.certresolver=default'
            - 'traefik.http.services.puff-smith-staging-tls.loadbalancer.server.port=3000'

    postgres:
        image: postgres:14.2
        ports:
            - "5532:5432"
        networks:
            - db
            - mongo
        environment:
            POSTGRES_USER: puff-smith
            POSTGRES_DB: puff-smith
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    mongo:
        image: mongo:5
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: agenda
        networks:
            - mongo

networks:
    web:
        external: true
    db:
    mongo:
