version: '3.4'
services:
    app:
        image: marekhanzal/puff-smith:staging
        env_file: .env
        networks:
            - web
            - db
            - mongo
            - maildev
        labels:
            - 'traefik.enable=true'
            # http stuff
            - 'traefik.http.routers.puff-smith-staging.rule=Host(`staging.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-staging.entrypoints=http'
            - 'traefik.http.routers.puff-smith-staging.middlewares=redirect-to-https'
            - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
            # https stuff
            - 'traefik.http.routers.puff-smith-staging-tls.rule=Host(`staging.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-staging-tls.entrypoints=https'
            - 'traefik.http.routers.puff-smith-staging-tls.tls=true'
            - 'traefik.http.routers.puff-smith-staging-tls.tls.certresolver=default'
            - 'traefik.http.services.puff-smith-staging-tls.loadbalancer.server.port=3000'

    maildev:
        image: soulteary/maildev
        networks:
            - web
            - maildev
        labels:
            - 'traefik.enable=true'
            # http stuff
            - 'traefik.http.routers.puff-smith-staging-maildev.rule=Host(`mail.staging.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-staging-maildev.entrypoints=http'
            - 'traefik.http.routers.puff-smith-staging-maildev.middlewares=redirect-to-https'
            - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
            # https stuff
            - 'traefik.http.routers.puff-smith-staging-maildev-tls.rule=Host(`mail.staging.puff-smith.rocks`)'
            - 'traefik.http.routers.puff-smith-staging-maildev-tls.entrypoints=https'
            - 'traefik.http.routers.puff-smith-staging-maildev-tls.tls=true'
            - 'traefik.http.routers.puff-smith-staging-maildev-tls.tls.certresolver=default'
            - 'traefik.http.services.puff-smith-staging-maildev-tls.loadbalancer.server.port=1080'

    postgres:
        image: postgres:14.2
        env_file: .env
        networks:
            - db
            - mongo
        environment:
            POSTGRES_USER: puff-smith
            POSTGRES_DB: puff-smith

    mongo:
        image: mongo:5
        env_file: .env
        environment:
            MONGO_INITDB_DATABASE: agenda
        networks:
            - mongo

networks:
    web:
        external: true
    db:
    mongo:
    maildev:
